### PR TITLE
Add 'control_structures' entries for Scala for issue #115.

### LINKED ISSUE #115: Add Scala control structures
# Description

The control structures (loops, ifs, etc.) in Scala are presently not on Code Thesaurus. I would love to see this added.

# Requirements

* Copy `web/thesauruses/_meta/control_structures.json` to a `web/thesauruses/scala/` directory
* Edit the control_structures.json file to accurately reflect Scala and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on more specifics of implementing this.

### PR DESCRIPTION
**Pull request by hypatian**
Might be some things in the wrong concepts, need to get some feedback on that.

## 📝 What type of PR is this? (check all applicable)

- [x] Data update

## 📖 Description

Added entries for most of the applicable control structures concepts for Scala 2.13 (issue #115). There are some cases where I'm uncertain whether I should be aiming for "if someone is using this concept in another language, what do they want to do in Scala?" or "what is the exact mechanism for doing this specific syntactic thing in Scala, and if it doesn't have it don't include it".

### CODE REVIEW

**Comment by hypatian** [comment]
Like in the pull request for issue #103, I've included some variations to demonstrate that you can use a single expression or a block for most of these.

For "ternary conditional", I've taken this concept to mean "how do you conditionally use different values in an expression?" In Scala, there's no separate concept for this--all "if"s are expressions. I still gave an example and called this out in the comment.

For "until loop" and "do until loop", I did _not_ include any examples for these, even though the "how do you loop based on something being _not_ true_" answer is "just negate the condition". This seemed to match how other languages were treating this.

For "for loop", I used this as a space to give an example of a simple numeric loop. It's unclear to me whether this concept is meant to be a numbered loop, or it's meant to be a C-style for loop with init, update, and test expressions.

For "foreach loop", I included some additional features since Scala's "for" is a general comprehension mechanism, including taking input from multiple sources, and filtering. And including producing structured results or executing for each combined entry.

For the "foreach", "map", and "filter" iteration categories, I gave both a method-call based approach, and also the for-loop based approach that does precisely the same thing (including generally calling the same methods).

For "recursion" iteration, I included nothing because I have no idea what this concept is meant to be--there's no discussion of what the concepts mean in general, and there are no examples of this one yet, it seems.

**Comment by hypatian** [comment]
@geekygirlsarah I guess the remaining open question I have is "what is 'recursion_iteration' meant to be?" Since there's no description and no examples, I'm not sure how to approach this.

**Comment by hypatian** [comment]
I updated this to be in-line with the changes I made to PR #210.

I'd still like to include a definition for 'recursion_iteration' if possible. I don't know whether that's intended to be tail recursion, recursive iteration over nested lists, or what.

**Comment by geekygirlsarah** [comment]
> @geekygirlsarah I guess the remaining open question I have is "what is 'recursion_iteration' meant to be?" Since there's no description and no examples, I'm not sure how to approach this.

I removed this. It was getting asked too often and the original person that put it in couldn't remember what it was for. You can remove it too!

Once you do that, (and optionally pull in changes from `codethesaurus/codethesaur.us:main`, this is good to merge!

**Comment by geekygirlsarah** [comment]
This PR won't deploy correctly unless you merge in the latest changes from `main`. It's due to some changes in `settings.py`. I can merge this without that working.

**Comment by geekygirlsarah** [comment]
You force-pushed so I couldn't see what you changed easily. I looked it all over again and I think it's right. I'll merge it in!

Thank you! I hope you have a good weekend!

**Comment by hypatian** [comment]
> You force-pushed so I couldn't see what you changed easily. I looked it all over again and I think it's right. I'll merge it in!

Still working out How Things Ought To Be Done On Github. :) Sorry about that. I was just trying to rebase up to main, but failing. And also I removed the no-longer-needed recursive iteration. Sorry for the spam!

Glad to help, you have a good weekend, too!

**Comment by geekygirlsarah** [comment]
I don't have a lot of "right ways to do it" here. also the settings updates were _very_ needed (security and convenience and speed) but it broke a LOT of PRs so I'm not surprised there was trouble. Sorry you got caught up in that!

**Pull request merged**
