### PR TITLE
Fix Reference lookups aren't logged in database in views.py

### LINKED ISSUE #723: Bug: Reference lookups aren't logging in database
# Expected Behavior

Any reference page lookup should be storing what was looked up in the web_lookupdata table in the database

# Actual Behavior

No lookup data is saving

# Steps to Reproduce the Problem

1. Lookup something (like Python version 3 functions)
1. Look inside the SQLite (locally) or Postgres (if you set it up) to see the row isn't in there

# Additional Info

Appears one hasn't been stored since Feb 2023. Maybe a migration could be added to catch this back up.

### PR DESCRIPTION
**Pull request by Frederic-Chopin**
## What GitHub issue does this PR apply to?

 

Resolves #723

## What changed and why?

    - Fixed issue where reference page lookups were not being stored in the database.
   - Modified `concepts` function in `views.py` to call `store_lookup_info` even when only one language is present.

## Checklist

   

- [X] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?
tested locally and now reference page lookup is stored in the web_lookupdata table in the database

### CODE REVIEW

**Comment by geekygirlsarah** [comment]
Such a simple fix! I told myself I'd go dig after work and you beat me to it!

How would you feel about making some unit tests that call the compare and reference pages and ensure it logs a visit? (You can say no since it's easy to call the page but checking the storage of it is a bit more complicated.)

**Review by geekygirlsarah — APPROVED** [review]

**Comment by Frederic-Chopin** [comment]
Hi Sarah, sure, I can try adding some unit tests over the weekend!

**Comment by geekygirlsarah** [comment]
@Frederic-Chopin Are you still working on this? If not, I can merge and maybe split off the tests as another issue. Let me know!

**Comment by Frederic-Chopin** [comment]
Hi Sarah, sorry for the late reply. I think it's best to split the test as another issue, thank you !

**Comment by geekygirlsarah** [comment]
I made #725 for it. If you want to work on that, go claim it. If not, I may get to it soon.

Thanks for working on this! I'll merge it in.

**Pull request merged**
