### PR TITLE
database creation

### LINKED ISSUE #495: [Idea] Publish stats page of visits of looked up data and/or missing data
# Description

In #480, @hegold suggested "Publish data on oops page visits so contributors can see the most requested missing items". I also thought a stats page of most commonly looked up comparisons or reference sheets would be interesting. Perhaps a "Stats" page at the top of the site along with different types of data looked up from the database?

This issue is to think through how this might work or what this might look like.

# Additional Notes

Since early March, lookups have been tracked in a database. There's presently no record on whether the lookup passed or failed, but this data can be used towards this.

This issue probably needs to be thought about a bit more before assigning to work on.

### PR DESCRIPTION
**Pull request by sarthakjalan05**
## What GitHub issue does this PR apply to?

 

Resolves #495 

## What changed and why?

 To publish a stats page of visits, as well as track missing data in your project, you can implement a logging or analytics system.

## Checklist

   

- [x] I claimed any associated issue(s) and they are not someone else's
- [ ] I have looked at documentation to ensure I made any revisions correctly
- [ ] I tested my changes locally to ensure they work
- [ ] For language files, I have validated the edited files are valid JSON and data shows up correctly
- [ ] For website code edits, I have added or edited any appropriate unit tests for my changes

### CODE REVIEW

**Comment by geekygirlsarah** [comment]
Hey @sarthakjalan05, #495 is for actually publishing an actual stats page. You made a temp page and some JS for it that looks like it might set some sample things up, but it's not done and that page isn't actually linked anywhere. Also the database tables already exist (tables `web_lookupdata` and `web_sitevisit`, see `web/migrations/0001_initial.py` for the file that sets it up) so no SQL files are necessary for this.

Go look around again and let me know if you need any help or if maybe you don't want to work on this issue anymore.

**Comment by sarthakjalan05** [comment]
@geekygirlsarah I tried to work on that but couldnt find a solution

**Comment by geekygirlsarah** [comment]
> @geekygirlsarah I tried to work on that but couldnt find a solution

Do you want me to try to explain more, or would you rather not work on the issue?

**Comment by sarthakjalan05** [comment]
> > @geekygirlsarah I tried to work on that but couldnt find a solution
> 
> Do you want me to try to explain more, or would you rather not work on the issue?
@geekygirlsarah i would rather not work because I tried to solve but couldn't find a solution. Thanks for considering my help

**Pull request closed without merging**
