### PR TITLE
Added data types in Lua

### LINKED ISSUE #580: [Lua] Add data types
# Description

Data types for Lua aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Directions

* On the home page, on the right side (the reference sheet side), choose the language and version, and then the concept.
* The page says the data doesn't exist, but clicking the arrow for the template will provide the template and file for you to use.
* Save that file in `/web/thesauruses/[language]/[version]/data_types.json`.
* Fill out all of the `"code"` sections.
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.
* Add in `"comment":` if you wish to explain something in the code
* Delete the `"name":` fields before your PR
* Save, commit your code, push to your fork, then make a PR.
* Watch the checks to make sure they all pass. If they don't, click on "Details" and it should tell you what to modify.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

### PR DESCRIPTION
**Pull request by ayaan-qadri**
## What GitHub issue does this PR apply to?

 

Resolves #580 

## What changed and why?

   I added data type feature for Lua as per issue #580 

## Checklist

   

- [X] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

Last year(Hacktoberfest2022) i worked for Lua language for codethesaur.us so i have already familiar with this project.

### CODE REVIEW

**Comment by ayaan-qadri** [comment]
Please add 'hacktoberfest-accepted' label if you are satisfied with PR.

**Comment by geekygirlsarah** [comment]
Hey, thanks for adding this! 

First, can you leave a comment on #580 to claim it as yours? (You checked it on the PR but you didn't actually do it.) Sometimes multiple people try to work on an issue together and it sucks that someone doesn't know someone else is working on it.

Second, the whole project is opted in to Hacktoberfest, no label needed on the PR.

Third, multiple things like signed and unsigned 8-bit integers are "Undefined" because you didn't specify if they do or don't exist in the language. You should fill those in and if the language doesn't have them, mark them as "not-implemented". (See the documentation on why.) You can use the `python manage.py generate_template` command to generate a full template to fill in the gaps you're missing.

image

**Review by geekygirlsarah — CHANGES_REQUESTED** [review]
Missing concepts leaving "unknown" answers on the pages.

**Comment by ayaan-qadri** [comment]
First of all sorry for not commenting on issue and checked it.

Second if this project opted into hacktoberfest still PR/MERGE need label look:

-



third, i have done "not-implement":true still it shows unknown… idk why?

**Comment by geekygirlsarah** [comment]
#692 isn't accepted because I haven't merged it in yet. When I do merge it, it should go into waiting and then be approved after 7 days. (This works for everyone so far, including me.)

image

https://github.com/thecuriousteam/pyliblog should automatically work because `hacktoberfest` is tagged on the project. (The other hacktoberfest tags don't matter. I add things like `hacktoberfest2023` in case people search for them.) So 
image

For the `not-implemented` part, some of the fields say "Not implemented in this langauge." Those are right. The fields that aren't are "unknown" because the fields are missing. Those are the fields that need to be added in. 

Ex: signed 8-bit integers are "unknown" because 
```
    "signed_integer_8_bit": {
      "name": "Signed 8-bit integer",
      "code": [
        ""
      ]
    },
```
is missing.

**Comment by ayaan-qadri** [comment]
Okayy, I'll correct it soon.

**Comment by ayaan-qadri** [comment]
btw @geekygirlsarah, this same thing is also happening in Python's data types.

**Review by geekygirlsarah — APPROVED** [review]
Thanks for adding the other fields back in. I'll approve and merge! Happy Hacktoberfest!

**Comment by geekygirlsarah** [comment]
> btw @geekygirlsarah, this same thing is also happening in Python's data types.

Yes, Python, C++, and Java data types were the first 3 things added to CT back in 2017 or so. The data types concept has evolved since then and no one's gone back to update them. There's a few other holes in thesauruses and just merged in a feature to point out they could be contributed to.

**Comment by ayaan-qadri** [comment]
> > btw @geekygirlsarah, this same thing is also happening in Python's data types.
> 
> Yes, Python, C++, and Java data types were the first 3 things added to CT back in 2017 or so. The data types concept has evolved since then and no one's gone back to update them. There's a few other holes in thesauruses and just merged in a feature to point out they could be contributed to.

I see, I'm planning to close all issue related to Lua then i would like resolve it.

**Pull request merged**
