### PR TITLE
Added functions in Lua

### LINKED ISSUE #582: [Lua] Add functions
# Description

Functions for Lua aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Directions

* On the home page, on the right side (the reference sheet side), choose the language and version, and then the concept.
* The page says the data doesn't exist, but clicking the arrow for the template will provide the template and file for you to use.
* Save that file in `/web/thesauruses/[language]/[version]/functions.json`.
* Fill out all of the `"code"` sections.
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.
* Add in `"comment":` if you wish to explain something in the code
* Delete the `"name":` fields before your PR
* Save, commit your code, push to your fork, then make a PR.
* Watch the checks to make sure they all pass. If they don't, click on "Details" and it should tell you what to modify.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

### PR DESCRIPTION
**Pull request by ayaan-qadri**
## What GitHub issue does this PR apply to?

 

Resolves #582

## What changed and why?

   I have added functions in Lua.

## Checklist

   

- [X] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

### CODE REVIEW

**Review by geekygirlsarah — CHANGES_REQUESTED** [review]
For most of these, they just need the function declaring line, or maybe the function declaring line and `end`. We want to try to keep it simpler.

For a few of the other spots, we try to keep from inventing algorithms here. Though a concept may not exist and you can invent it, don't. This should just be the language reference. Leaving a comment can be fine but if the language doesn't do it, it's `not-implemented`.

See https://codethesaurus-test-pr-697.herokuapp.com/compare/?concept=functions&lang=lua%3B5&lang=javascript%3BECMAScript+2023 (review app for the PR) or https://codethesaur.us/reference/?concept=functions&lang=javascript%3BECMAScript+2023 (on CT) for a simpler example.

Make some of those changes then we can merge it.

**Comment by ayaan-qadri** [comment]
> For most of these, they just need the function declaring line, or maybe the function declaring line and `end`. We want to try to keep it simpler.
> 
> For a few of the other spots, we try to keep from inventing algorithms here. Though a concept may not exist and you can invent it, don't. This should just be the language reference. Leaving a comment can be fine but if the language doesn't do it, it's `not-implemented`.
> 
> See https://codethesaurus-test-pr-697.herokuapp.com/compare/?concept=functions&lang=lua%3B5&lang=javascript%3BECMAScript+2023 (review app for the PR) or https://codethesaur.us/reference/?concept=functions&lang=javascript%3BECMAScript+2023 (on CT) for a simpler example.
> 
> Make some of those changes then we can merge it.

i will think about that concept and if i get any idea,I will let you know and I'll correct the file soon.

**Review by geekygirlsarah — APPROVED** [review]
This looks pretty good and much simpler now! I'll merge it in. Happy Hacktoberfest!

**Comment by geekygirlsarah** [comment]
Also I'm not sure why I can't update the branch here (guessing a setting on your CT repo) but I'll merge it anyway.

**Pull request merged**
