### PR TITLE
Added functions for BASH

### LINKED ISSUE #236: Add Bash functions
# Description

The Bash scripting language is presently not on Code Thesaurus. I would love to see this added and the functions concept added to CT.

# Requirements

* Copy `web/thesauruses/_meta/data_types.json` to a `web/thesauruses/bash/` directory
* Edit the data_types.json file to accurately reflect Bash and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on more specifics of implementing this.

### PR DESCRIPTION
**Pull request by cfilipiak31**
Added new functions.json for BASH and updated meta_info to include it for issue #236 

## 📝 What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## 📖 Description

Added BASH functions to thesaurus.

## ✅ QA Instructions, Screenshots

Check that JSON file exists. Run codethesaur.us and view BASH functions page.

Screen Shot 2021-07-13 at 10 45 05 PM

### CODE REVIEW

**Comment by geekygirlsarah** [comment]
I like this and appreciate it so far. The anonymous functions part was cut out. Is that because it doesn't exist in Bash? If so, could you add a key ` "not-implemented": true` to the parts so that Code Thesaurus knows they don't exist in the language (as opposed to what it shows now which is just "unknown"). I'll be happy to approve it after that!

**Comment by geekygirlsarah** [comment]
@cfilipiak31 Hi! I was going to check in on this to see how it's coming along and if you have any questions for me or anything since it's been about a month since your original PR creation.

**Comment by cfilipiak31** [comment]
@geekygirlsarah Sorry! I had put this down for a while, but think I've added the correct changes now. Let me know if there's anything else I can change.

**Comment by geekygirlsarah** [comment]
@cfilipiak31 Adding the `not-implemented` helps! I think the comment I added about explaining what `$1` and such are in a `comment` section would be helpful, especially for those not familiar with how those work in Bash. If you could add that, I'd be happy with this!

**Comment by cfilipiak31** [comment]
Thanks for the reminder! I added comments to make it more clear, but can't find your original request so let me know if there is any more to change

**Comment by geekygirlsarah** [comment]
I think this looks good! Thank you for working on this and making the updates!

**Pull request merged**
