### PR TITLE
Add queues/stacks structure/concept file

### LINKED ISSUE #520: Add the "Queues/stacks" structure
Add queues and stacks as a concept/structure!

### PR DESCRIPTION
**Pull request by geekygirlsarah**
## What GitHub issue does this PR apply to?

 

Resolves #520 

## What changed and why?

   

This adds stacks and queues to the structures

## (If editing Django app) Please add screenshots

   
image

## Checklist

   

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [x] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

   

I'm open to anyone's suggestions on what to add/remove/change/etc.

### CODE REVIEW

**Review by colindean — APPROVED** [review]

**Comment by mrdowden** [comment]
There are a few additional concepts I can think of that might be interesting here, but they could also add unwanted complexity or be too niche to be universally applicable.

1. Backing Data Structure

For example, JavaScript provides Stack & Queue operations on top of an Array. Java provides a single Stack/Queue interface but the backing data structure can be selected at creation time. This can have performance or garbage collection implications based upon the use case.

This can possibly be answered in the creation section, but if this is intended a not to that effect might make sense.

2. Iteration

Is the data structure iterable for a read-only presentation of the contents? If so, is this available only front to back or also in reverse?

3. Type Conversion

Can this type be converted to another type? If so, which ones and how is this done.

**Comment by geekygirlsarah** [comment]
oooh, good points @mrdowden! thanks!

**Comment by geekygirlsarah** [comment]
@mrdowden I added all the things! I might pull this in but if you or @colindean think of anything else, feel free to let me know!

**Comment by mrdowden** [comment]
This is awesome! I think I may need to go update some languages now. :smile:

**Comment by geekygirlsarah** [comment]
Thanks! And that's up to you...  I'd also always take another buddy on a live stream too...

**Pull request merged**
