### PR TITLE
Added simple feature request and bug report templates

### LINKED ISSUE #28: Feature: Add New Issue templates
I would like a templates so when one creates an issue, you can choose from a bug report or a feature enhancement. This will make it easier and more consistent for me to add new things for others, but also for others to add new issues too.

See: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates on how to do it

Ideas of templates: https://github.com/stevemao/github-issue-templates/

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

### PR DESCRIPTION
**Pull request by sehqlr**
This is the first iteration of creating these new Issue Templates. Because I don't have access to the web GUI for creating these, I am attempting to create this manually.

I expect to have a lot of back and forth on this to add all the information that we need for feature requests, including things like assigning to a particular person and so on.

### CODE REVIEW

**Comment by sehqlr** [comment]
Mentioning #28 to link them

**Comment by geekygirlsarah** [comment]
So far so good! 👍 

You definitely don't NEED the web GUI for this, you can do it manually on your own machine. (Unfortunately you can't "test" it until merged but there's many examples out there.) It's also why I linked a few things on the issue too.

You don't have to include person assigning on the issue, I'm sort of doing that as people claim them in comments, so don't worry about that part. Just like some basics for bugs and features like on those examples.

**Comment by geekygirlsarah** [comment]
@sehqlr Any updates on the other template?

**Comment by sehqlr** [comment]
I've got a preliminary version of both feature request and issue templates pushed to this branch. If these templates meet with your approval, I suggest that we merge this PR and we can test out making new issues with them, then we can create additional PRs to refine them as the project moves forward. That way, I can focus on doing something else on the project for my 3 other PRs for Hacktoberfest.

**Comment by geekygirlsarah** [comment]
This will probably be fine. I can fine-tune it from here if I feel there needs to be any changes.

Thanks! If you want more PRs for Hacktoberfest, there's more things in issues or you can contribute to the language code files. Many other projects could use help too!

**Pull request merged**
