### PR TITLE
Added the requested changes for Golang Logic/Math Operators

### LINKED ISSUE #300: Add Go Logic/Math Operators
# Description

Logic/Math Operators for Go aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/operators.json` to the right Go directory in `web/thesauruses/`
* Edit the operators.json file to accurately reflect the latest major version of Go
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

### PR DESCRIPTION
**Pull request by 26tanishabanik**
## What GitHub issue does this PR apply to?

Resolves #300 

## Checklist

- [x] I claimed any associated issue(s) and they are not someone else's
- [x] I have looked at documentation to ensure I made any revisions correctly
- [x] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

### CODE REVIEW

**Comment by geekygirlsarah** [comment]
Checks pass and it looks alright to me. I'll merge it in.

Thanks for working on this! I appreciate it!

**Comment by 26tanishabanik** [comment]
> Checks pass and it looks alright to me. I'll merge it in.
> 
> Thanks for working on this! I appreciate it!

Thanks a lot for giving me an opportunity to work on this

**Comment by geekygirlsarah** [comment]
I appreciate people willing to work on CT to help make it a really useful tool that many people can hopefully use!

**Comment by 26tanishabanik** [comment]
> I appreciate people willing to work on CT to help make it a really useful tool that many people can hopefully use!

True

**Pull request merged**
