### PR TITLE
Issue 679 add language basics

### LINKED ISSUE #679: [Structure] Add language basics
# Description

This issue is for adding a new structure for all languages that will let you compare a new aspect of a language. Ideally someone with many programming languages will help work on this.

This structure should be a way to describe language basics. This could be:

* Features of the language like whether it's compiled or interpreted, is static or dynamically typed, or is open source or not
* What the entry point of a program is (a main function? top of a file?)
* How do you add comments to a file?
* Is the language extensible (by internal or external libraries) and how you include those
* What's the most minimal program you can have?

Or other things. It should take some thought on all of the features that any programming language could have. Upon making this PR, expect it to have some revisions as people from various programming language backgrounds offer suggestions.

# Requirements

1. Look over the documentation at https://docs.codethesaur.us/thesaurus/add-new-structure/
2. Add a new file under `web/thesauruses/_meta` named whatever feels appropriate
3. Open up `web/thesauruses/meta_info.json` and add your new file to that file in the `structures` section.
4. Add in some categories, then add in the concepts under that
5. Feel free to use any `_meta` file as examples for how to do it
6. Make a PR and we can help test and review it

### PR DESCRIPTION
**Pull request by sayantandasgupta**
## What GitHub issue does this PR apply to?

 

Resolves #679 

## What changed and why?

   
Added the basic details regarding the structure or features of any programming language including features like

- Type Systems
- Paradigm Category
- Level of Abstraction
- Execution Domain
- Application Domain
- Memory Management

## Checklist

   

- [x] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [ ] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

### CODE REVIEW

**Comment by geekygirlsarah** [comment]
The Validate Meta Info File failed because:
>  `web/thesauruses/_meta/language_basics.json` is not listed as a structure in `meta_info.json`
If you add language basics to web/thesauruses/meta_info.json, that should pass.

**Comment by sayantandasgupta** [comment]
Oh. Shoot! I must have missed it. So sorry about that. Am fixing it right away

**Review by geekygirlsarah — CHANGES_REQUESTED** [review]
I think this is fine, but I mention a few things in #679 that I think you could add on here too. Could you add those please?

**Comment by sayantandasgupta** [comment]
Of course. I was prepared for any additional features it may require. I will work on those right away

**Comment by sayantandasgupta** [comment]
@geekygirlsarah I have added the following features

- Entry Point of a Language
- How to add comments
- Library and Framework Support
- Minimal Program to write

**Review by geekygirlsarah — APPROVED** [review]
This is a pretty good start I think! I might tweak it a bit on my own. It's good enough to merge, I think.

Thank you for adding this! Happy Hacktoberfest!

**Comment by sayantandasgupta** [comment]
Thank You for helping me out. Would like to contribute more in the future

**Comment by sayantandasgupta** [comment]
Just one tiny thing. My PR is showing as Not Accepted on Hacktoberfest website. I don't know why @geekygirlsarah

**Comment by geekygirlsarah** [comment]
They refresh the stats periodically, it's not instantaneous. Check back in a few hours. If it's still not in the waiting period, let me know!

**Pull request merged**
