### PR TITLE
Fix misspelled key name s/bitwise_and_assignmnet/bitwise_and_assignment/

### LINKED ISSUE #638: "Bitwise AND and assignment operator" not rendered properly in a few languages
# Language

- C# 9
- ECMAScript 2020
- ECMAScript 2021

# Wrong Field(s)
1. `Bitwise AND and assignment operator`

# Additional Information

The information is present for these languages, but the key is misspelled (probably a copy/paste error across).

# Disclaimer
Will claim this one.

### PR DESCRIPTION
**Pull request by jeff303**
## What GitHub issue does this PR apply to?

Resolves #638

## What changed and why?

Rename keys so these rows are correctly rendered

## Checklist

   

- [X] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

### CODE REVIEW

**Review by gutogalego — APPROVED** [review]
nice catch!

**Comment by ulyssear** [comment]
The "operators" concept has been updated for javascript (all versions) in PR #631 of which this problem has already been fixed.
I think it's better to merge this one before #631.

**Comment by ulyssear** [comment]
On my side, i use this custom Dockerfile (which works fine)

```Dockerfile
FROM python:3-slim
ENV PYTHONBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN python -m pip install -U pip \ 
    && apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2 \
    && pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD python manage.py migrate && python manage.py runserver 0.0.0.0:8000
```

**Review by geekygirlsarah — APPROVED** [review]
Good catch! I'll merge it in. Thanks for finding this!

**Pull request merged**
