### PR TITLE
Added info which are generating errors

### LINKED ISSUE #243: 404 error pages should include details to add language data
# Description

When someone looks up a concept in a language, and it doesn't exist yet, it will show a 404 error page that tells that it's missing. I would like the page to show how to contribute that information if the user would like, both the documentation reference and what the file would be in Github.

# Requirements

* The error page should still display an error.
* Below that, it should offer the above ways to contribute
* It should name the location and filename of what it would be (`web/thesauruses/[language]/[concept].json`) and link to the repo, and possibly GitHub's online editor if it lets you do that
* It should also link to the docs (docs.codethesaur.us) on how to contribute

# Additional Notes

Leave a comment to say you're going to work on it and I'll assign you. 

Also leave a comment if you have any questions or want to discuss anything about the ticket.

See docs.codethesaur.us for more details on how to contribute!

### PR DESCRIPTION
**Pull request by unnati914**
## 📝 What type of PR is this? (check all applicable)
 Fixes #243 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## 📖 Description

_Please replace this line with a description of the changes.

## ✅ QA Instructions, Screenshots

_Please replace this line with instructions on how to test your changes.

### CODE REVIEW

**Review by aryasoni98 — APPROVED** [review]

**Comment by geekygirlsarah** [comment]
@unnati914 I appreciate you trying to work on this, but I think the original context of the issue was missed. I tried to clarify it a bit, but I don't want to link to where the error is getting thrown, I want to link to what the future thesaurus file would be. (So if a concept isn't explained in a language yet, it'd show what that file should be and where it would be located in the repository.)

If you want to fix that, I'd appreciate that. Thank you!

**Comment by unnati914** [comment]
sure

**Comment by geekygirlsarah** [comment]
Hey @unnati914, how is this going? Do you have any questions I can help answer?

**Comment by geekygirlsarah** [comment]
Hi @unnati914, since I haven't heard from you in over 3 weeks since my last comment, I'm going to go ahead and close this PR and take you off the issue. If you want back on, let me know and I can reopen this or add you back to the issue.

**Pull request closed without merging**
