### PR TITLE
adds operators for rlang

### LINKED ISSUE #577: Add R language
# Language you would like added
R  
[R project](https://www.r-project.org/about.html)

# Information on the language
This is a language primarily for stats that has grown into a popular tool for data science that is being used to create webpages and books, so it is more flexible than originally imagined.

# Disclaimer
If you would like to work on this issue, please comment here so that you are assigned.
I'd like to work on this issue

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
## What GitHub issue does this PR apply to?

 

Resolves #577 
Continuation of resolution for 577

## What changed and why?

 added operators.json that was not included before

## Checklist

   

- [x] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

### CODE REVIEW

**Comment by monkeywithacupcake** [comment]
I'm going to try to get the other files done later this week for Rlang.

**Comment by cafce25** [comment]
Even if #577 is already closed I think linking context is fine and without Resolves or similar in front it won't affect the issue anyways

**Comment by geekygirlsarah** [comment]
> Even if #577 is already closed I think linking context is fine and without Resolves or similar in front it won't affect the issue anyways

Yeah, in this case you can link it. It'll just re-close. (I could re-open it if that makes you happy too.)

**Review by geekygirlsarah — APPROVED** [review]
Looks good to me! I think I can merge it.

Thanks for adding some more R!

**Pull request merged**
