### PR TITLE
Github action to test docker container build

### LINKED ISSUE #677: Add GitHub Action to test the build of Docker containers
# Description

It's possible to make changes to the `Dockerfile` or `docker-compose.yml` files and they might fail. This feature is to add a GitHub Action (either preexisting from elsewhere or make your own steps) to build it to make sure it works.

# Requirements

* Should be added somewhere in the workflows of CT, or it's own workflow

# Additional Notes

### PR DESCRIPTION
**Pull request by ulyssear**
## What GitHub issue does this PR apply to?

Resolves #677

## What changed and why?

   A github action has been created which checks docker container build.

## Checklist

- [ ] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

I know I didn't claim this pull request before. I hope this can be merged.

### CODE REVIEW

**Comment by Anurag-Nagpal** [comment]
Hey @ulyssear, I had also tried this but my github-action always failed:-
https://github.com/Anurag-Nagpal/codethesaur.us/actions/runs/6669393621/job/18127070143

I see your github-action is also failing with the same error, downloading requirements.txt in docker(specifically package psycopg2-binary-2.9.5).
```
 Error: pg_config executable not found.
```
**I am curious how you will handle this error to pass the github-action, I am now able to figure out how to resolve this.**
cc: @geekygirlsarah 

my changes for reference only: https://github.com/Anurag-Nagpal/codethesaur.us/blob/main/.github/workflows/docker-build-test.yml

**Comment by ulyssear** [comment]
Hello ! I resolved the issue in this pull request : https://github.com/codethesaurus/codethesaur.us/pull/665#issuecomment-1783784264

**Review by geekygirlsarah — APPROVED** [review]
I'll tentatively approve this but won't merge until the other PR that changes Dockerfile is merged, and we retest this. Thanks!

**Comment by ulyssear** [comment]
I removed Dockerfile of the indexed files in PR #665

**Review by geekygirlsarah — APPROVED** [review]
The test works but fails because the Docker container needs an update, so I can merge this in (and we hopefully fix this soon).

Thank you!

**Pull request merged**
