### PR TITLE
Adds rlang

### LINKED ISSUE #577: Add R language
# Language you would like added
R  
[R project](https://www.r-project.org/about.html)

# Information on the language
This is a language primarily for stats that has grown into a popular tool for data science that is being used to create webpages and books, so it is more flexible than originally imagined.

# Disclaimer
If you would like to work on this issue, please comment here so that you are assigned.
I'd like to work on this issue

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
## What GitHub issue does this PR apply to?

 

Resolves #577

## What changed and why?

Add R language and started adding concepts. This adds R as r in the meta_lang; creates a folder for r version 4 and creates classes and io files for R

## Checklist

   

- [X] I claimed any associated issue(s) and they are not someone else's
- [X] I have looked at documentation to ensure I made any revisions correctly
- [X] I tested my changes locally to ensure they work
- [ ] (If editing Django) I have added or edited any appropriate unit tests for my changes

## Any additional comments or things to be aware of while reviewing?

 Will Still need to add other concept files. This gets R started.

### CODE REVIEW

**Review by geekygirlsarah — APPROVED** [review]
Ah, the memories of fighting R at my last job come back to me...

Looks good! I think I can merge it. Thank you for adding this!

**Comment by geekygirlsarah** [comment]
If you haven't already, you should register for Hacktoberfest. You're on your way to getting the shirt and swag already!

**Comment by monkeywithacupcake** [comment]
I love R, and I still found this little bit kind of painful. It's not where my headspace is when using R at all.

**Comment by geekygirlsarah** [comment]
> I love R, and I still found this little bit kind of painful.

Thanks for working on this anyway! lol

**Pull request merged**
