### PR TITLE
Issue 21 homepage design

### LINKED ISSUE #21: Feature: Work on home page design
**Description:**
The home page of CT has a basic Bootstrap setup but it's not really well done. It's technically "responsive" but isn't really set up for great mobile viewing. I'd like to see this either redesigned entirely or have some of the issues fixed so it works a little better.

**Requirements:**:
* Has the main navigation bar have both a Home and About page. This menu will need to grow as time goes on.
* It has a similar introductory description paragraph talking about the project
* Has two sections for the "Learn a Language" and "See a Reference Sheet", both with drop down boxes like they have now.
* A footer at the bottom with a link to the project itself. (This can stay the same as it is now.)
* It should stay fairly simple but if you want to add a front-end framework, discuss it below and why you think it would be good to have it. 

**Notes:**
Files to modify are in `web/templates` or `web/static`.

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

### PR DESCRIPTION
**Pull request by pattimcletchie**
Removed SCSS files and moved everything to `app.css` file. Changed colors to be AAA friendly and added in W3 accessibility for the buttons and dropdowns. Updated the mobile navigation to be easier too get to.

Closes #21

### CODE REVIEW

**Comment by pattimcletchie** [comment]
@geekygirlsarah I can't figure out how to merge the branch conflicts within VSCode. It says my branch is up to date with master... so I'm not sure how to resolve those.

**Comment by geekygirlsarah** [comment]
I'll see if I can try to resolve them @pattimcletchie

**Comment by pattimcletchie** [comment]
@geekygirlsarah figured out the merge conflicts. This should be ready for review

**Comment by geekygirlsarah** [comment]
I like it! I might tweak the colors a bit but appreciate the work! I'll merge it in.

Have a lovely weekend!

**Pull request merged**
